# data_products.py
products = [
    {
        "id": 1,
        "name": "Smartphone X",
        "brand": "TechMaster",
        "category": "Electronics",
        "description": "Latest smartphone with 128GB storage and 5G connectivity. Amazing camera and battery life.",
        "base_price": 29999,
        "rating": 4.5,
        "reviews_count": 1240,
        "stock": 45,
        "delivery_days": 2,
        "image_url": "https://picsum.photos/id/0/200/200"
    },
    {
        "id": 2,
        "name": "Laptop Pro",
        "brand": "CompuMax",
        "category": "Electronics",
        "description": "High performance laptop with 16GB RAM, 512GB SSD, and Intel i7 processor.",
        "base_price": 59999,
        "rating": 4.7,
        "reviews_count": 890,
        "stock": 12,
        "delivery_days": 3,
        "image_url": "https://picsum.photos/id/1/200/200"
    },
    {
        "id": 3,
        "name": "Wireless Earbuds",
        "brand": "SoundBeats",
        "category": "Electronics",
        "description": "Noise cancellation earbuds with 24hr battery life and Bluetooth 5.2.",
        "base_price": 3999,
        "rating": 4.3,
        "reviews_count": 2350,
        "stock": 78,
        "delivery_days": 1,
        "image_url": "https://picsum.photos/id/2/200/200"
    },
    {
        "id": 4,
        "name": "The Lost World",
        "brand": "Penguin Books",
        "category": "Books",
        "description": "Adventure novel about dinosaurs and a hidden jungle plateau.",
        "base_price": 499,
        "rating": 4.1,
        "reviews_count": 320,
        "stock": 5,
        "delivery_days": 4,
        "image_url": "https://picsum.photos/id/3/200/200"
    },
    {
        "id": 5,
        "name": "Healthy Recipes Cookbook",
        "brand": "KitchenPress",
        "category": "Books",
        "description": "100 healthy recipes for modern living, including vegan and gluten-free options.",
        "base_price": 799,
        "rating": 4.6,
        "reviews_count": 567,
        "stock": 23,
        "delivery_days": 3,
        "image_url": "https://picsum.photos/id/4/200/200"
    },
    {
        "id": 6,
        "name": "Men's Running Shoes",
        "brand": "SportFit",
        "category": "Clothing",
        "description": "Lightweight running shoes with cushioning and breathable mesh.",
        "base_price": 2499,
        "rating": 4.4,
        "reviews_count": 1870,
        "stock": 32,
        "delivery_days": 2,
        "image_url": "https://picsum.photos/id/5/200/200"
    },
    {
        "id": 7,
        "name": "Women's Handbag",
        "brand": "Luxora",
        "category": "Clothing",
        "description": "Designer handbag with leather finish and multiple compartments.",
        "base_price": 3999,
        "rating": 4.2,
        "reviews_count": 434,
        "stock": 8,
        "delivery_days": 3,
        "image_url": "https://picsum.photos/id/6/200/200"
    },
    {
        "id": 8,
        "name": "Smart Watch",
        "brand": "TechMaster",
        "category": "Electronics",
        "description": "Track fitness, heart rate, and notifications with a sleek AMOLED display.",
        "base_price": 4999,
        "rating": 4.5,
        "reviews_count": 2100,
        "stock": 56,
        "delivery_days": 2,
        "image_url": "https://picsum.photos/id/7/200/200"
    },
    {
        "id": 9,
        "name": "Android Tablet",
        "brand": "CompuMax",
        "category": "Electronics",
        "description": "10-inch display with stylus support, ideal for notes and media.",
        "base_price": 18999,
        "rating": 4.3,
        "reviews_count": 654,
        "stock": 19,
        "delivery_days": 3,
        "image_url": "https://picsum.photos/id/8/200/200"
    },
    {
        "id": 10,
        "name": "Space Odyssey",
        "brand": "Galaxy Publishing",
        "category": "Books",
        "description": "Sci-fi epic about space travel, alien civilizations, and human destiny.",
        "base_price": 599,
        "rating": 4.8,
        "reviews_count": 921,
        "stock": 44,
        "delivery_days": 2,
        "image_url": "https://picsum.photos/id/9/200/200"
    },
    {
        "id": 11,
        "name": "Winter Jacket",
        "brand": "OutdoorGear",
        "category": "Clothing",
        "description": "Warm jacket for cold weather with water-resistant shell.",
        "base_price": 4999,
        "rating": 4.4,
        "reviews_count": 312,
        "stock": 11,
        "delivery_days": 4,
        "image_url": "https://picsum.photos/id/10/200/200"
    },
    {
        "id": 12,
        "name": "Digital Camera",
        "brand": "OptiShot",
        "category": "Electronics",
        "description": "24MP camera with 4K video recording and interchangeable lenses.",
        "base_price": 34999,
        "rating": 4.7,
        "reviews_count": 508,
        "stock": 7,
        "delivery_days": 5,
        "image_url": "https://picsum.photos/id/11/200/200"
    }
]